### PR TITLE
Fix: Fix SVG added with wrong dimensions

### PR DESCRIPTION
**Pull request by marsiancba**
Fixes bug that if you add SVG to CNC/Laser then resulting dimensions do not match dimensions spcified in the SVG file.

### CODE REVIEW

**Comment by marsiancba** [comment]
https://github.com/Snapmaker/Luban/issues/502

**Comment by parachvte** [comment]
@marsiancba 

Thanks for your input.

Only change `sourceWidth / DEFAULT_SCALE` will lead to other bugs when processing the model (image) and recovering image from project file. We are looking into this issue for a while, when several refactors finishes we will rework on the scale thing.

**Comment by marsiancba** [comment]
@parachvte 

Thank you for your response. I have checked this only in the browser (`npm run dev`) and there I have not noticed any problems, all seems to work ok. I would like to check also project saving/loading but have troubles running it in electron (in WSL).

**Comment by parachvte** [comment]
Fixed by https://github.com/Snapmaker/Luban/pull/773 and https://github.com/Snapmaker/Luban/pull/778.

Under testing.

**Pull request closed without merging**
