### PR TITLE
Improvement: Ukrainian translation

### PR DESCRIPTION
**Pull request by Andygol**
key-App/Settings/Pop up a reminder when importing deficient model(s)

Enable Ooze Shield

New strings

200W CNC

Ironing

Combing

Seam

### CODE REVIEW

**Comment by Andygol** [comment]
re: https://github.com/parachvte/ProfileDocs/pull/1

**Comment by parachvte** [comment]
@Andygol 

Seems like the i18next is broken due to the introduce of new JS grammar (optional chaining) and TypeScript.
I'll need to fix the i18next scanner before I can merge your PR.

**Comment by parachvte** [comment]
> Seems like the i18next is broken due to the introduce of new JS grammar (optional chaining) and TypeScript.
I'll need to fix the i18next scanner before I can merge your PR.

Been fixed in #1816 

Please resolve conflicts in your PR to make it able to merge.

**Comment by Andygol** [comment]
@parachvte, conflicts are resolved, PR ready for merge

**Pull request merged**
