### PR TITLE
Fix winget releaser workflow

### PR DESCRIPTION
**Pull request by vedantmgoyal9**

### CODE REVIEW

**Comment by parachvte** [comment]
@vedantmgoyal2009 

Do we need to add a repo protection for WinGet workflow?

I drafted a release on my own repo, and the action ran:
https://github.com/parachvte/Luban/actions/runs/3384551800

While this is only a test build, we need withdraw the publish and make publishes only run main repo.

**Comment by vedantmgoyal2009** [comment]
you can add `if: github.repository == 'Snapmaker/Luban`' in the workflow to prevent running on forks.

**Comment by vedantmgoyal2009** [comment]
BTW, it seems like the workflow didn't run:
image

**Comment by parachvte** [comment]
Yeah. The protection `if: github.repository == 'Snapmaker/Luban'` is already in the releaser step...

**Pull request merged**
