### PR TITLE
Update resource.json

### PR DESCRIPTION
**Pull request by Minimieo**
### More german translations

Improvment
<BLANK LINE>
Add many german translations, in the future i planned much more improvments. If you have a contact to the sales department. I'll be very glade if you able to support me. I urgent need an enclosre ;-)

### CODE REVIEW

**Comment by jane-rose** [comment]
Since we have updated the german translation(from an external translation agency), could you help to check it? 
If find any unreasonable translation, you can update it on this pr. Thanks. @Minimieo

**Comment by Minimieo** [comment]
@jane-rose:
No Problem.
What bad timing, no problem i will check the translation from agency.
So the translation is already merged into the master branch?
Should i reload/refresh from the master?

**Comment by jane-rose** [comment]
Yep, is already merged into the master, u can refresh/pull from the master. And we will merge your pr in 4.2 later version(since our v4.2.1-beta version will be released on Feb 22).

**Comment by jane-rose** [comment]
Please solve the conflicts, then we will merge this pr.

**Pull request closed without merging**
