### PR TITLE
Build: Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @Snapmaker.

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@jane-rose any updates?

**Comment by jane-rose** [comment]
OK, I will follow this tonight.

**Comment by vedantmgoyal2009** [comment]
@jane-rose Done 👍

**Comment by jane-rose** [comment]
@vedantmgoyal2009  Help us to test? 
image

**Comment by vedantmgoyal2009** [comment]
The action is working fine and we are ready to merge the PR.

**Comment by vedantmgoyal2009** [comment]
@jane-rose The action is working fine and we are ready to merge the PR.

**Pull request merged**
