### PR TITLE
Improvement: Update i18n translation for Ukrainian 

### PR DESCRIPTION
**Pull request by Andygol**
Here is the updated Ukrainian translation. 

It was not test locally because of https://github.com/Snapmaker/Luban/issues/1638, but I expect that everything has to be OK. 😉

### CODE REVIEW

**Comment by jane-rose** [comment]
> Here is the updated Ukrainian translation.
> 
> It was not test locally because of #1638, but I expect that everything has to be OK. 😉

Issue #1638 is resolved. About this pr you may need to resolve the conflict or do it myself.

**Comment by Andygol** [comment]
Cool, I'll do conflict resolution and inform you @jane-rose

**Comment by Andygol** [comment]
@jane-rose, this PR is ready for merge.

I see that you started to rebuild UI and some parts of it doesn't have proper value.
image

I'm looking forward to further updates. 👌

**Review by jane-rose — APPROVED** [review]

**Comment by jane-rose** [comment]
> @jane-rose, this PR is ready for merge.
> 
> I see that you started to rebuild UI and some parts of it doesn't have proper value. image
> 
> I'm looking forward to further updates. 👌

Yep, is still in testing. Merged.

**Pull request merged**
