### PR TITLE
Fix: Allow sidebars to scroll independently of main window

### PR DESCRIPTION
**Pull request by adamphillips**
Had a go at resolving https://github.com/Snapmaker/Luban/issues/500

There are a bunch of different ways of doing this kind of thing so I thought I'd suggest one and get some feedback.

This seemed like the least intrusive way of making the change but I'm happy to try again in a different way if someone can point me in the direction you'd prefer.

### CODE REVIEW

**Comment by parachvte** [comment]
Nice try one the sidebar 😃 
We have primary sidebar and secondary sidebar both may causing the overscroll.

**Comment by adamphillips** [comment]
Ah ok. I had seen the primary scrollbar but didn't realise it could go that large.
Shall I apply a similar fix to the primary scrollbar as well then?

**Comment by jane-rose** [comment]
Cool, nice try! I will send a pr to fix the bug.

**Comment by parachvte** [comment]
> Ah ok. I had seen the primary sidebar but didn't realise it could go that large.

Widgets can be dragged between 2 bars.

Seems like @jane-rose has found another issue here (relates to mouse event handling).
You can discuss the issue with him, or check the option to allow maintainer to modify so we can make changes on your code.

**Comment by adamphillips** [comment]
Right ok.

@jane-rose  I am happy to carry on working on it if you want to point me in the direction you want to go. Otherwise the option to allow edits is also checked so feel free to make the changes yourself if you prefer.

Thanks!

**Comment by jane-rose** [comment]
https://github.com/Snapmaker/Luban/pull/557

**Comment by adamphillips** [comment]
Great, shall I close this PR then in favour of the newer one?

**Comment by jane-rose** [comment]
Definitely u can

**Pull request closed without merging**
