### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by parachvte**

### CODE REVIEW

**Comment by Andygol** [comment]
👀 Looking forward for [other languages](https://crowdin.com/project/luban). It would be great if you could find a way to add existing translations to Crowdin.

**Comment by parachvte** [comment]
> 👀 Looking forward for [other languages](https://crowdin.com/project/luban). It would be great if you could find a way to add existing translations to Crowdin.

Yes it can import existing translations.

Let me do some explore on zh-CN, and then add other languages.

**Comment by parachvte** [comment]
@Andygol 
https://crowdin.com/project/luban Should be working now for Ukrainian 🎉 
It will check and open pull request every 24 hours.

**Comment by Andygol** [comment]
@parachvte TY VM 🙏

**Comment by parachvte** [comment]
Great work! You are amazing!! 😆

**Pull request merged**
