### PR TITLE
Changed/Added German translations for v3.13.1

### PR DESCRIPTION
**Pull request by lichtwellenreiter**
Improvement: Change / Add  German translations for v3.13.1

Change / Add  German translations for v3.13.1

[https://github.com/Snapmaker/Luban/issues/794](https://github.com/Snapmaker/Luban/issues/794)

### CODE REVIEW

**Comment by jane-rose** [comment]
How is it going @parachvte

**Comment by parachvte** [comment]
@CJK is reviewing the translations, and merging it to v3.14.0.

**Comment by parachvte** [comment]
@lichtwellenreiter Could you rebase your branch onto latest `master`, and then force push again.

Our i18n translations has been updated according to #851

**Comment by parachvte** [comment]
All right I did the rebase for your branch, now merging it. @lichtwellenreiter

**Comment by odrobnik** [comment]
There are some very odd German localisations. Should I point them out to you, or should I send a pull request?

**Comment by lichtwellenreiter** [comment]
> There are some very odd German localisations. Should I point them out to you, or should I send a pull request?

You can send a pull request. I will look into the translations after 2-3 Releases

**Pull request merged**
